# Generated by Django 3.2.25 on 2024-03-25 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_voetbalspelers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voetbalspelers',
        ),
    ]
